# .render.yaml
services:
  - type: web
    name: parkguard-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: "cd backend && npm install && npm run build"
    startCommand: "cd backend && npm start"
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false